spring.application.name=tasks-api
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

# Enable detailed logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.example.tasks_api=DEBUG

# Show full error details
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

# Disable whitelabel error page
server.error.whitelabel.enabled=false